### ISSUE TITLE
Russian subtitles

### ISSUE THREAD

**Issue by DobryakJesus** [a-maliarov/awesome-shields#2]
Братан, идея супер, но нужны субтитры русские, а то авто субтитры гавнишко редкостное. Визуально все понятно, но на слух нет, я думаю я не один такой)

**Comment by a-maliarov** [comment]
Hah, nice issue style though :D
No problems, will add the subtitles!

**Comment by DobryakJesus** [comment]
О уже сделано, красавчик вообще! Оперативно работаешь)))

**Comment by a-maliarov** [comment]
You're welcome)
